# Generated by Django 5.1.5 on 2025-01-30 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fituser', '0003_customuser_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('activity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StrengthTrainingWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('activity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightGainWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('activity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightLossWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('activity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('strength_building', 'Strength Building'), ('rehabilitation', 'Rehabilitation')], max_length=50)),
                ('workout_id', models.IntegerField()),
                ('status', models.CharField(choices=[('not_completed', 'Not Completed'), ('completed', 'Completed')], default='not_completed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
