# Generated by Django 5.1.5 on 2025-02-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fituser', '0005_alter_customuser_options_customuser_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recommended_goal',
            field=models.CharField(choices=[('weight_gain', 'Weight Gain (Strength Training)'), ('strength_training', 'Strength Training'), ('weight_loss', 'Weight Loss'), ('rehabilitation', 'Rehabilitation / Special Training'), ('no_data', 'No BMI Data Available')], default='no_data', max_length=50),
        ),
    ]
