# Generated by Django 5.1.5 on 2025-02-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fituser', '0006_customuser_recommended_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkouttracking',
            name='workout_id',
        ),
        migrations.AddField(
            model_name='userworkouttracking',
            name='workout_day',
            field=models.CharField(default='not assigned', max_length=20),
        ),
    ]
