# Generated by Django 5.1.5 on 2025-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fituser', '0007_remove_userworkouttracking_workout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkouttracking',
            name='workout',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userworkouttracking',
            name='workout_day',
            field=models.CharField(max_length=20),
        ),
    ]
